module.exports = function(code) {
    switch(code) {
        case 'AD': return 'Andorra';
        case 'AE': return 'Emiratos Árabes Unidos';
        case 'AM': return 'Armenia';
        case 'AR': return 'Argentina';
        case 'AT': return 'Austria';
        case 'AU': return 'Australia';
        case 'BE': return 'Bélgica';
        case 'BG': return 'Bulgaria';
        case 'BM': return 'Bermudas';
        case 'BR': return 'Brasil';
        case 'CA': return 'Canadá';
        case 'CH': return 'Suiza';
        case 'CL': return 'Chile';
        case 'CN': return 'China';
        case 'CO': return 'Colombia';
        case 'CR': return 'Costa Rica';
        case 'CU': return 'Cuba';
        case 'CZ': return 'República Checa';
        case 'DE': return 'Alemania';
        case 'DK': return 'Dinamarca';
        case 'DO': return 'República Dominicana';
        case 'DZ': return 'Argelia';
        case 'EC': return 'Ecuador';
        case 'EE': return 'Estonia';
        case 'EG': return 'Egipto';
        case 'ES': return 'España';
        case 'FI': return 'Finlandia';
        case 'FR': return 'Francia';
        case 'GB': return 'Reino Unido';
        case 'GE': return 'Georgia';
        case 'GR': return 'Grecia';
        case 'GT': return 'Guatemala';
        case 'HK': return 'Hong Kong';
        case 'HR': return 'Croacia';
        case 'HU': return 'Hungría';
        case 'IE': return 'Irlanda';
        case 'IL': return 'Israel';
        case 'IN': return 'India';
        case 'IO': return 'Territorio Británico del Océano Índico';
        case 'IS': return 'Islandia';
        case 'IT': return 'Italia';
        case 'JP': return 'Japón';
        case 'KE': return 'Kenya';
        case 'KR': return 'República de Corea';
        case 'LB': return 'Líbano';
        case 'LR': return 'Liberia';
        case 'LT': return 'Lituania';
        case 'MD': return 'Moldavia';
        case 'MT': return 'Malta';
        case 'MX': return 'México';
        case 'MY': return 'Malasia';
        case 'NG': return 'Nigeria';
        case 'NL': return 'Países Bajos';
        case 'NO': return 'Noruega';
        case 'NZ': return 'Nueva Zelanda';
        case 'PA': return 'Panamá';
        case 'PE': return 'Perú';
        case 'PL': return 'Polonia';
        case 'PR': return 'Puerto Rico';
        case 'PT': return 'Portugal';
        case 'RE': return 'Reunión';
        case 'RS': return 'Serbia';
        case 'RU': return 'Rusia';
        case 'SE': return 'Suecia';
        case 'SG': return 'Singapur';
        case 'SI': return 'Eslovenia';
        case 'SL': return 'Sierra Leona';
        case 'SV': return 'El Salvador';
        case 'SZ': return 'Swazilandia';
        case 'TR': return 'Turquía';
        case 'TW': return 'Taiwan';
        case 'UA': return 'Ucrania';
        case 'UG': return 'Uganda';
        case 'US': return 'Estados Unidos';
        case 'UY': return 'Uruguay';
        case 'VE': return 'Venezuela';
        case 'VI': return 'Islas Vírgenes de los Estados Unidos';
        case 'YT': return 'Mayotte';
        case 'ZA': return 'Sudáfrica';
        default: return code;
    }
}
